Backend feature/update models
bounswe/bounswe2020group8 pull request #198
Opened 2020-12-01 19:50 UTC by mtyazici

Things done for this PR:
- I added two new models named customer and vendor. They inherit from client model. 
- I put the common endpoints for customer and vendor to a common router named `client`. 
- I changed the controllers, services and routers so that vendor and customer models could be accessed via our API.
- I deleted Google functionality from vendor model.

Things to be done in future:
- We should create the necessary models for fields in vendor and customer model. Right now their type are all strings.
- I updated the api-docs but they could be improved.
- We could reduce signupWithGoogle and loginWithGoogle to only SigninWithGoogle

2020-12-02 15:34 UTC, oztasozgurcan commented on backend/models/vendor.js
> +var customerSchema = new Schema(
@mtyazici var vendorSchema = new Schema(

2020-12-02 15:34 UTC, oztasozgurcan commented on backend/models/vendor.js
> +ClientBase.discriminator("Vendor", customerSchema);
ClientBase.discriminator("Vendor", vendorSchema);

2020-12-02 15:37 UTC, oztasozgurcan requested changes
@mtyazici I've commented necessary changes, sorry not to change on-review. 😁

2020-12-02 16:44 UTC, mtyazici commented on backend/models/vendor.js
> +var customerSchema = new Schema(
updated :+1:

2020-12-02 16:44 UTC, mtyazici commented on backend/models/vendor.js
> +ClientBase.discriminator("Vendor", customerSchema);
updated :+1:

2020-12-02 16:47 UTC, mtyazici commented
> @mtyazici I've commented necessary changes, sorry not to change on-review. grin

That's fine :smile:  But I think it is better to show changes here so we can commit them right on the website.

2020-12-03 16:45 UTC, oztasozgurcan approved these changes
@mtyazici now it seems just fine 💯  way to go 🚀

2020-12-03 18:34 UTC, merged