Web feature/address payment api
bounswe/bounswe2020group8 pull request #290
Opened 2020-12-24 18:05 UTC by ykaya932

- Connected the address and payment page to the backend.
- Used `services.js` to get the base url

2020-12-26 21:18 UTC, afraarslan requested changes
I think it needs some changes.

* Check the `PaymentInfo.js` screen and the `Request.js` file for undefined values.
* Delete console logs except for errors (Errors may help when debugging)
* Delete unused variables

2020-12-26 21:18 UTC, afraarslan commented on web/carousel/src/apis/Account/Requests.js
> +      console.log(res.data.data[field]);
we can delete these console logs since there are tons of them. :sweat_smile:

2020-12-26 21:18 UTC, afraarslan commented on web/carousel/src/apis/Account/Requests.js
> +      console.log(res.data.data[field]);
I realized that this console log gives an undefined error. Can you check if there is a mistake here?

2020-12-26 21:33 UTC, ykaya932 commented on web/carousel/src/apis/Account/Requests.js
> +      console.log(res.data.data[field]);
Sure, thanks for the review!

2020-12-26 21:52 UTC, ykaya932 commented on web/carousel/src/apis/Account/Requests.js
> +      console.log(res.data.data[field]);
Thanks for pointing that error out. Now, I am making sure that at least the list is an empty list :+1:

2020-12-26 23:25 UTC, ahmetyigitgedik approved these changes
Thanks for your effort 💯

2020-12-27 10:09 UTC, afraarslan approved these changes
Problems are solved.Thanks  :robot:

2020-12-27 15:30 UTC, merged